export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";
export const SET_USER_DATA_FAILURE = "SET_USER_DATA_FAILURE";
export const COLLECT_USER = "COLLECT_USER";
export const COLLECT_USER_SUCCESS = "COLLECT_USER_SUCCESS";
export const COLLECT_USER_FAILURE = "COLLECT_USER_FAILURE";

